//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCodeCorrector.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizableResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizableResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCodeCorrector.Resources.LocalizableResources", typeof(LocalizableResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поток на сокращаемом участке в долях от номинального потока:.
        /// </summary>
        internal static string EndLineCount {
            get {
                return ResourceManager.GetString("EndLineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка конца линии включена.
        /// </summary>
        internal static string EndLineEnabled {
            get {
                return ResourceManager.GetString("EndLineEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры обработки конца линии.
        /// </summary>
        internal static string EndLineParams {
            get {
                return ResourceManager.GetString("EndLineParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина сокращаемого участка, мм:.
        /// </summary>
        internal static string EndLineSize {
            get {
                return ResourceManager.GetString("EndLineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить данные в файл.
        /// </summary>
        internal static string ErrorDuringRecordingToFile {
            get {
                return ResourceManager.GetString("ErrorDuringRecordingToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Режим с поиском сопряжённых линий (на данный момент работает не всегда и очень медленно).
        /// </summary>
        internal static string FindOtherLines {
            get {
                return ResourceManager.GetString("FindOtherLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть файл.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете файл gcode для коррекции.
        /// </summary>
        internal static string OpenFileTitle {
            get {
                return ResourceManager.GetString("OpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корректор g-code файлов.
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработать и сохранить файл.
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете куда сохранить обработанный файл.
        /// </summary>
        internal static string SaveFileTitle {
            get {
                return ResourceManager.GetString("SaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение результатов.
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обработка начала линии включена.
        /// </summary>
        internal static string StartLineEnabled {
            get {
                return ResourceManager.GetString("StartLineEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры обработки начала линии.
        /// </summary>
        internal static string StartLineParams {
            get {
                return ResourceManager.GetString("StartLineParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл успешно сохранён.
        /// </summary>
        internal static string SuccessfullySaved {
            get {
                return ResourceManager.GetString("SuccessfullySaved", resourceCulture);
            }
        }
    }
}
